# Generated by Django 5.2.4 on 2025-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
