# Generated by Django 5.2.4 on 2025-11-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotelvendor_business_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenetiess',
            new_name='ameneties',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Ameneties',
            new_name='ameneties',
        ),
    ]
