# Generated by Django 5.2.4 on 2025-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_amenetiess_ameneties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
